const QUESTIONS=["I found it hard to wind down.","I was aware of dryness of my mouth.","I couldn't seem to experience any positive feeling at all.","I experienced breathing difficulty (e.g. excessively rapid breathing, breathlessness in the absence of physical exertion).","I found it difficult to work up the initiative to do things.","I tended to over-react to situations.","I experienced trembling (e.g. in the hands).","I felt that I was using a lot of nervous energy.","I was worried about situations in which I might panic and make a fool of myself.","I felt that I had nothing to look forward to.","I found myself getting agitated.","I found it difficult to relax.","I felt down-hearted and blue.","I was intolerant of anything that kept me from getting on with what I was doing.","I felt I was close to panic.","I was unable to become enthusiastic about anything.","I felt I wasn't worth much as a person.","I felt that I was rather touchy.","I was aware of the action of my heart in the absence of physical exertion.","I felt scared without any good reason.","I felt that life was meaningless."];
const GROUPS={Depression:[2,4,9,12,15,16,20],Anxiety:[1,3,6,8,14,18,19],Stress:[0,5,7,10,11,13,17]};
const OPTIONS=['Did not apply to me at all','Applied to me to some degree, or some of the time','Applied to me to a considerable degree, or a good part of the time','Applied to me very much, or most of the time'];
let session=JSON.parse(sessionStorage.getItem('tsSession')||'null'),activeType='',current=0,answers=[];
const $=s=>document.querySelector(s); const show=id=>document.querySelectorAll('.view').forEach(x=>x.classList.toggle('hidden',x.id!==id));
function toast(message){const t=$('#toast');t.textContent=message;t.className='show';setTimeout(()=>t.className='',2800)}
function severity(name,score){const r={Depression:[[9,'Normal'],[13,'Mild'],[20,'Moderate'],[27,'Severe'],[99,'Extremely severe']],Anxiety:[[7,'Normal'],[9,'Mild'],[14,'Moderate'],[19,'Severe'],[99,'Extremely severe']],Stress:[[14,'Normal'],[18,'Mild'],[25,'Moderate'],[33,'Severe'],[99,'Extremely severe']]};return r[name].find(x=>score<=x[0])[1]}
const DEMO_KEY='tattvaSaarathiLocalDemo';
const demoState=()=>JSON.parse(localStorage.getItem(DEMO_KEY)||'{"clients":[],"reports":[]}');
const saveDemo=data=>localStorage.setItem(DEMO_KEY,JSON.stringify(data));
async function localDemoApi(path,body={}){const db=demoState();const fail=message=>{throw new Error(message)};if(path==='/admin/login'){if(body.email!=='tattvasaarathi@gmail.com'||body.password!=='123Abc123@')fail('Incorrect administrator credentials.');return{token:'local-admin'}}if(path==='/login'){const client=db.clients.find(x=>x.username===body.username&&x.password===body.password);if(!client)fail('Incorrect username or password.');const reports=db.reports.filter(x=>x.clientId===client.id);return{token:'local-'+client.id,name:client.name,tests:Object.fromEntries(reports.map(r=>[r.type,r]))}}if(!session?.token)fail('Please sign in again.');if(path==='/admin/clients'){if(session.token!=='local-admin')fail('Administrator access required.');if(db.clients.some(x=>x.username===body.username))fail('That username already exists.');db.clients.push({id:crypto.randomUUID(),...body});saveDemo(db);return{ok:true}}if(path==='/admin/reports'){if(session.token!=='local-admin')fail('Administrator access required.');return{reports:db.reports.map(r=>({...r,clientName:db.clients.find(c=>c.id===r.clientId)?.name||'Client'})).reverse()}}if(path==='/submit'){const clientId=session.token.replace('local-','');if(db.reports.some(r=>r.clientId===clientId&&r.type===body.type))fail('This assessment has already been completed.');const prior=db.reports.filter(r=>r.clientId===clientId);if((body.type==='mid'||body.type==='post')&&!prior.some(r=>r.type==='pre'))fail('Complete the pre assessment first.');const scores=Object.fromEntries(Object.entries(GROUPS).map(([name,ids])=>[name,ids.reduce((sum,index)=>sum+body.answers[index],0)*2]));const report={clientId,type:body.type,scores,severity:Object.fromEntries(Object.entries(scores).map(([name,score])=>[name,severity(name,score)])),createdAt:new Date().toISOString()};db.reports.push(report);saveDemo(db);return{report,tests:Object.fromEntries(db.reports.filter(r=>r.clientId===clientId).map(r=>[r.type,r]))}}fail('Not found.')}
async function api(path,body){if(location.protocol==='file:')return localDemoApi(path,body);const response=await fetch('/.netlify/functions/api?route='+encodeURIComponent(path),{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(session?.token?{Authorization:'Bearer '+session.token}:{})},body:body?JSON.stringify(body):undefined});const contentType=response.headers.get('content-type')||'';if(!contentType.includes('application/json'))throw new Error('The site backend is not deployed yet. Deploy the Netlify function and try again.');const data=await response.json();if(!response.ok)throw new Error(data.error||'Something went wrong.');return data}
function goHome(){session=null;sessionStorage.removeItem('tsSession');show('welcomeView')}
$('#signIn').onclick=$('#startButton').onclick=()=>show('loginView');document.querySelectorAll('[data-home]').forEach(b=>b.onclick=goHome);
$('#loginButton').onclick=async()=>{try{const data=await api('/login',{username:$('#username').value.trim(),password:$('#password').value});session={...data,role:'client'};sessionStorage.setItem('tsSession',JSON.stringify(session));openDashboard()}catch(e){$('#loginError').textContent=e.message}};
$('#logout').onclick=goHome;
function openDashboard(){show('dashboardView');$('#greeting').textContent='Welcome, '+session.name+'.';const tests=session.tests||{};[['pre',true],['mid',!!tests.pre],['post',!!tests.pre]].forEach(([type,available])=>{const card=$('#'+type+'Card'),done=!!tests[type],button=card.querySelector('button');card.classList.toggle('locked',!available);button.disabled=!available;button.textContent=done?'View report':available?(type==='mid'?'Start reflection':'Start assessment'):'Locked';button.onclick=()=>done?loadReport(tests[type]):startTest(type)});}
function startTest(type){activeType=type;current=0;answers=Array(21);$('#testType').textContent=(type==='mid'?'MID REFLECTION':type.toUpperCase()+' ASSESSMENT');show('assessmentView');renderQuestion()}
function renderQuestion(){const n=current+1;$('#questionCounter').textContent=`Question ${n} of 21`;$('#percent').textContent=Math.round(n/21*100)+'%';$('#progress').style.width=(n/21*100)+'%';$('#questionText').textContent=QUESTIONS[current];$('#previous').disabled=!current;$('#next').textContent=current===20?'Complete assessment →':'Next question →';$('#options').innerHTML=OPTIONS.map((label,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" ${answers[current]===i?'checked':''}><b>${i}</b><span>${label}</span></label>`).join('');$('#options').onchange=e=>{answers[current]=Number(e.target.value);$('#answerStatus').textContent='Answer saved'}}
$('#previous').onclick=()=>{if(current){current--;renderQuestion()}};$('#leaveTest').onclick=openDashboard;
$('#next').onclick=async()=>{if(answers[current]===undefined){toast('Please choose one answer to continue.');return}if(current<20){current++;renderQuestion();return}if(answers.some(x=>x===undefined)){toast('Please complete every question.');return}try{const data=await api('/submit',{type:activeType,answers});session.tests=data.tests;sessionStorage.setItem('tsSession',JSON.stringify(session));loadReport(data.report)}catch(e){toast(e.message)}};
function loadReport(report){show('resultView');$('#reportMeta').textContent=`${report.type.toUpperCase()} ASSESSMENT · ${new Date(report.createdAt).toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}`;$('#scores').innerHTML=Object.entries(report.scores).map(([name,value])=>`<article class="score"><span>${name}</span><b>${value}<small> / 42</small></b><em>${report.severity[name]}</em></article>`).join('');const highest=Object.entries(report.scores).sort((a,b)=>b[1]-a[1])[0];$('#supportTitle').textContent=`${highest[0]} needs the most attention right now.`;$('#supportText').textContent='Your scores reflect your answers for the past week. If difficult feelings continue or get worse, please consider speaking to a qualified mental-health professional. If you are in immediate danger, contact emergency services.';window.currentReport=report}
$('#returnDashboard').onclick=()=>{if(confirm('Screenshot required: please confirm that you have saved a screenshot of this result.'))openDashboard()};$('#downloadResult').onclick=()=>window.print();
$('#adminButton').onclick=()=>$('#adminDialog').showModal();$('#adminLogin').onclick=async e=>{e.preventDefault();try{const data=await api('/admin/login',{email:$('#adminEmail').value.trim(),password:$('#adminPassword').value});session={...data,role:'admin'};sessionStorage.setItem('tsSession',JSON.stringify(session));$('#adminDialog').close();openAdmin()}catch(err){$('#adminError').textContent=err.message}};
async function openAdmin(){show('adminView');try{const data=await api('/admin/reports');$('#reportList').innerHTML=data.reports.length?data.reports.map(r=>`<div class="report-row"><div><b>${r.clientName}</b><small>${r.type.toUpperCase()} · ${new Date(r.createdAt).toLocaleString('en-IN')}</small></div><div>D ${r.scores.Depression} · A ${r.scores.Anxiety} · S ${r.scores.Stress}</div></div>`).join(''):'<p class="fine">No reports yet.</p>'}catch(e){toast(e.message)}}
$('#clientForm').onsubmit=async e=>{e.preventDefault();try{await api('/admin/clients',{name:$('#clientName').value.trim(),email:$('#clientEmail').value.trim(),username:$('#clientUsername').value.trim(),password:$('#clientPassword').value});e.target.reset();toast('Client login created successfully.')}catch(err){toast(err.message)}};$('#adminLogout').onclick=goHome;
if(session?.role==='client')openDashboard();if(session?.role==='admin')openAdmin();
